[window]
decorations = "Full"
dynamic_padding = true

[font]
size = 8.0
normal = { family = "0xProto Nerd Font", style = "Regular" }

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.normal]
black   = "#21222c"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#f8f8f2"

