#!/bin/sh

exec 2>&1
printf "Loading modules...\n" | ~/.config/statusbar/dwmsetbar && sleep 1

sec=0

# Internet
update_internet () {
    internet="^b#1b1d2b^^c#86e1fc^$(~/.config/statusbar/sb_internet)^d^"
}

# Battery
update_battery () {
    battery="^c#c8d3f5^BAT: $(~/.config/statusbar/sb_battery)^d^"
}

# Datetime
update_datetime () {
    datetime="^b#1b1d2b^^c#828bb8^$(date "+%b %d %Y (%a) %H:%M") "
}

update_record() {
    recordingicon="^c#ff757f^$(cat /tmp/recordingicon 2>/dev/null)^d^"
}


update_cpu() {
    cpu="^c#ffb86c^$(~/.config/statusbar/sb_cpu)^d^"
}

# update_bluetooth() {
#     bluetooth="^c#50fa7b^$(~/.config/statusbar/sb_bluetooth)^d^"
# }


display () {
    printf "%s\n" " $cpu | $battery | $internet | $datetime^d^$recordingicon" | ~/.config/statusbar/dwmsetbar
}

# signals for each module to update while updating display. RTMIN is 34
trap "update_volume;display"    "RTMIN"
trap "update_backlight;display" "RTMIN+1"
trap "update_pkgs;display"      "RTMIN+2"
trap "update_record;display"   "RTMIN+3"

while true
do
    # how many seconds each module updates
    [ $(( sec % 10  )) -eq 0 ] && update_internet
    [ $(( sec % 60   )) -eq 0 ] && update_battery
    [ $(( sec % 5    )) -eq 0 ] && update_datetime
    [ $(( sec % 5    )) -eq 0 ] && update_cpu
    # [ $(( sec % 5    )) -eq 0 ] && update_bluetooth

    # how often the display updates
    [ $((sec % 5 )) -eq 0 ] && display

    sleep 1 & wait && sec=$((sec + 1))
done
